#!/usr/bin/env python3
"""Compute the auto-raised SRAM memory map for the Sprinter target.

Phase-1 Scheme C lays the SRAM (#0000-#3FFF, WIN0/CACHE) out as:

    #0100  _SDK        hot SDK code (grows with build flags)
           _SDKDATA    SDK mutable data            (floor #1400)
           EVO tables  page table + saved + meta   (floor #1A00, size #600)
           stack       game stack, 1 KB            (-> top #23FF)
    #2400  _CODE       C image chunk0 (rest of C spills to DRAM chunks)

When build flags (FILEIO/SPRITE16/SAMPLE_ASYNC/NATIVE/UNROLL) grow `_SDK` past
its floor, the data / table region / stack / C entry must all shift up. This
reads the pass-1 link map (built with the FLOOR layout -- areas may overlap,
which sdld tolerates; only the area SIZES are read, and sizes are independent
of the base addresses) and computes the smallest layout that fits, never below
the floors -- so any build that already fits keeps byte-identical addresses.

Emits a make snippet (EVO_TABLES/SDKDATA_LOC/STACK_LOC/STACK_TOP/CODE_LOC) ONLY
when a raise above the floors is needed; otherwise the output file is left empty
so the caller keeps the floor layout (no second pass). See sprinter.mk.
"""
import argparse
import re
import sys

# Fixed region geometry (parity with the EvoSDK-derived floor layout).
SDK_LOC        = 0x0100
SDKDATA_FLOOR  = 0x1400
TABLES_FLOOR   = 0x1A00
TABLES_SIZE    = 0x0600   # page table (#100) + saved slots + meta/image table (#500)
STACK_SIZE     = 0x0400   # 1 KB game stack
ALIGN          = 0x10     # data/region alignment (minimal C-memory waste)


def align_up(addr, a=ALIGN):
    return (addr + a - 1) & ~(a - 1)


def area_size(map_text, name):
    """Return the byte size of a linker area from an sdld map (`-mjx` format)."""
    # e.g. "_SDK                               0100   0FF7 =   4087. bytes (REL,CON)"
    m = re.search(r'^%s\s+([0-9A-Fa-f]+)\s+([0-9A-Fa-f]+)\s*=' % re.escape(name),
                  map_text, re.MULTILINE)
    if not m:
        raise SystemExit("layout.py: area %s not found in map" % name)
    return int(m.group(2), 16)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--map', required=True, help='pass-1 link .map (floor layout)')
    ap.add_argument('--out', required=True, help='make snippet to write (empty if no raise)')
    args = ap.parse_args()

    with open(args.map) as f:
        text = f.read()

    sdk_size     = area_size(text, '_SDK')
    sdkdata_size = area_size(text, '_SDKDATA')

    sdkdata_loc = max(SDKDATA_FLOOR, align_up(SDK_LOC + sdk_size))
    evo_tables  = max(TABLES_FLOOR,  align_up(sdkdata_loc + sdkdata_size))
    stack_loc   = evo_tables + TABLES_SIZE
    stack_top   = stack_loc + STACK_SIZE - 1
    code_loc    = stack_loc + STACK_SIZE

    raised = (sdkdata_loc > SDKDATA_FLOOR) or (evo_tables > TABLES_FLOOR)

    if not raised:
        # Floors fit -> leave an empty snippet; caller keeps the floor layout.
        open(args.out, 'w').close()
        print("layout.py: floors OK (_SDK=%d -> end %#06x < %#06x, _SDKDATA=%d)"
              % (sdk_size, SDK_LOC + sdk_size, SDKDATA_FLOOR, sdkdata_size),
              file=sys.stderr)
        return

    if code_loc >= 0x4000:
        raise SystemExit("layout.py: CODE_LOC %#06x would leave no SRAM C chunk "
                         "(SDK too large for WIN0) -- reduce flags" % code_loc)

    with open(args.out, 'w') as f:
        f.write("# auto-generated by layout.py -- raised SRAM map (SDK overflows floor)\n")
        f.write("EVO_TABLES  := %#06x\n" % evo_tables)
        f.write("SDKDATA_LOC := %#06x\n" % sdkdata_loc)
        f.write("STACK_LOC   := %#06x\n" % stack_loc)
        f.write("STACK_TOP   := %#06x\n" % stack_top)
        f.write("CODE_LOC    := %#06x\n" % code_loc)

    print("layout.py: RAISED -> _SDKDATA %#06x, EVO_TABLES %#06x, stack..%#06x, "
          "_CODE %#06x (_SDK=%d, _SDKDATA=%d)"
          % (sdkdata_loc, evo_tables, stack_top, code_loc, sdk_size, sdkdata_size),
          file=sys.stderr)


if __name__ == '__main__':
    main()
