; =========================================================================
;  loader.asm -- Stage 2 direct low-address trampoline for Scheme C
; =========================================================================
;  This documents the tiny loader currently emitted by tools/dss_exe.py when
;  CODE_LOC is below the DSS direct EXE minimum (#4100).
;
;  It is intentionally not the final PRELOAD loader. DSS loads the whole EXE
;  body at LOADER_LOAD with LOADER=0; this trampoline copies the C image from
;  just after itself down to CODE_LOC (#2400), sets the EvoSDK-compatible stack,
;  and jumps to crt0 _entry.
;
;  Final Stage 2 will replace this with the PRELOAD file-reading loader that
;  allocates pages, reads/decompresses body blobs, maps Scheme C, and then jumps
;  to the same crt0 entry point.
; =========================================================================

LOADER_LOAD     =       0x4100
LOADER_SIZE     =       18      ; di + 3x(ld rr,nn) + ldir + ld sp,nn + jp nn
CODE_LOC        =       0x2400
CODE_SOURCE     =       LOADER_LOAD + LOADER_SIZE
CODE_SIZE       =       0       ; patched/generated by dss_exe.py
STACK_TOP       =       0x23FF

        .module loader
        .area   _CODE

_loader_entry::
        di
        ld      hl, #CODE_SOURCE
        ld      de, #CODE_LOC
        ld      bc, #CODE_SIZE
        ldir
        ld      sp, #STACK_TOP
        jp      CODE_LOC
