#!/usr/bin/env python3
# Generates alps_pal.h: the real 256-colour palette of alps.png as a C array, so
# the demo can compute desaturated / tinted variants in C and push them with
# pal_load256() (pal_copy only exposes the low 16 entries).
#
# Regenerate after changing alps.png:   python3 genpal.py
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "sprintersdk" / "tools"))
from assetpack import read_image

HERE = Path(__file__).resolve().parent
palette, _px, _w, _h, _bpp, _t = read_image(HERE / "alps.png")
pal = list(palette) + [(0, 0, 0)] * (256 - len(palette))   # pad to 256

lines = [
    "// Auto-generated by genpal.py from alps.png. Do not edit by hand.",
    "// 256 * (R8, G8, B8): the photo's real 256-colour master palette.",
    "static const u8 g_alps_pal[768] = {",
]
for i in range(256):
    r, g, b = pal[i]
    lines.append(f"\t{r},{g},{b},")
lines.append("};")
(HERE / "alps_pal.h").write_text("\n".join(lines) + "\n")
print(f"alps_pal.h written ({len(palette)} real colours, padded to 256)")
